apiVersion: apps/v1
kind: Deployment
metadata:
  name: jhttp
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: jhttp
  template:
    metadata:
      labels:
        app: jhttp
    spec:
      containers:
      - image: docker.io/v2/gabrielgagv/harness-se:13
        name: jhttp
        ports:
        - containerPort: 8080
